### ISSUE TITLE
Cannot play audio CD

### ISSUE THREAD

**Issue by glaubersm** [jonaski/strawberry#124]
Hi

I use strawberry-full-git on Arch Linux running KDE Plasma 5.15.4, installed from AUR.
When I click "Open audio CD" in "Music" menu, strawberry opens a new playlist.
The new playlist is empty and strawberry never plays the disc.
I can play the same disc with clementine installed on the same system.

**Comment by jonaski** [comment]
Works fine here, can you start strawberry from a terminal and see if there is any useful output?

**Comment by glaubersm** [comment]
Here is the output

```
13:21:22.952 DEBUG MainWindow:797                   Started
13:21:22.985 INFO  DeviceManager:381                Device added: "/dev/sr0" ("/dev/sr0")
13:21:23.012 WARN  IconLoader:71                    Couldn't load icon "cd" from system theme icons.
13:21:23.058 DEBUG PlaylistBackend:278              Saving playlist 1
13:21:30.971 INFO  SongLoaderInserter:100           Loading audio CD...
13:21:30.979 ERROR logging:60                       gst_element_make_from_uri: assertion 'gst_is_initialized ()' failed
13:21:31.049 DEBUG PlaylistBackend:278              Saving playlist 2
```

**Comment by jonaski** [comment]
Are you using xine or vlc in the engine settings? CD playback is only implemented with gstreamer.
Does it work if you select gstreamer?

**Comment by glaubersm** [comment]
I'm using vlc engine.
Maybe could you make "Open audio CD..." option greyed out when any engine but Gstreamer is selected in Strawberry settings?
Strawberry just emits noise here when I try to play files stored on my hard disk or an audio cd using Gdtreamer engine. The same occurs when I use Clementine and deadbeef playsers. There is some problem on my system, but it's an issue not related to Strawberry I suppose.
I think that you can close this report.

**Comment by jonaski** [comment]
Fixed https://github.com/jonaski/strawberry/commit/7a0f6684e58e79b91c8002475163d22c178fca74

**Comment by jonaski** [comment]
I think your noise problem is related to pulseaudio. If I enable pulseaudio it just emits really loud noise, I've always had problems with pulseaudio ever since it became default with the distros, I think that was around 2005, I never use pulseaudio and always uninstall it.
Try setting output to alsa, or just do sudo killall pulseaudio and see if you still have the problem.

**Comment by glaubersm** [comment]
I use Strawberry with pulseaudio on another distribution (Neon dev unstable) without any problem.
Unfortunately switching the output to alsa did not solve the problem on Arch Linux.

**Comment by PrSunflower** [comment]
Hello,

First thank you for developing Strawberry Music Player.

I have been looking for a replacement to Windows Media Player and found Strawberry on alternativeto.net, unfortunately I am having the same issue described above by @glaubersm .

Music > Open Audio CD but Strawberry opens new playlists that are empty.

![image](https://user-images.githubusercontent.com/59576952/76541193-7edb0e00-6483-11ea-9f8c-0a0db72b392e.png)


**Information:
Windows 10 Home 64-bit, version 1909.
I installed the "Windows 64 bit" installer found on the official webpage.** 

I have checked and WMP can read all audio tracks as well as VLC Media Player so the audio CD is correctly detected by my computer.

In the settings the engine used seems to be GStreamer, and it is greyed out so I cannot see other options :

![image](https://user-images.githubusercontent.com/59576952/76541531-088adb80-6484-11ea-824a-0489975d38bc.png)


@jonaski I would be glad if you could help me on this issue.

Kind regards

**Comment by jonaski** [comment]
CD playback doesn't work on Windows

**Comment by NucleaPeon** [comment]
@jonaski Is it a planned feature or is there a Windows-specific issue preventing this from being implemented?

**Comment by jonaski** [comment]
I looked into it a long time ago when I first setup the Windows cross build port using MXE, but I don't specifically remember what the issue was, I think the issue was in one of the libraries, but I dont remember exactly. It has never worked though, But a lot of the libraries have been updated since then.

**Comment by NucleaPeon** [comment]
@jonaski Maybe add the Help Wanted tag instead of closing the issue, it seems like cd playback is an expected feature. It would take the load off of you while allowing others to fill in the missing feature as well as document that it's a missing piece. Others might file the same issue.

**Comment by jonaski** [comment]
Yeah, but lets great a new issue for CD playback on Windows

**Comment by PrSunflower** [comment]
Ah it doesn't work on Windows yet, that's why...
Thank you for creating a new issue!

Keep it up with the development! Best regards
