### ISSUE TITLE
Feature request: Lyrics tags

### ISSUE THREAD

**Issue by yekteniya** [jonaski/strawberry#206]
Trying to move from Clementine to Strawberry, lyrics has been the feature that has been holding me back the most.

It'd be great (and sounds like an easy implementation) if you could make the lyrics tag from the music file be the primary source for lyrics and after that, if the tag is empty, continue searching with whatever is implemented already. 
Also an independent tab just for the lyrics (or the option for hiding the album cover in the context tab) or being able to edit the lyrics tag from within the music player would be nice, but I could live without it.

Keep up the good work 👍

**Comment by jonaski** [comment]
The lyrics from the tags are the primary source, it should only search if those are empty. Is it broken?

**Comment by yekteniya** [comment]
I'm in Version 0.5.5-120-gc92a796 using Debian Buster and it looks like its broken. I've looked into it with several files from completely different albums (all mp3s) and written with ID3 tag version 2.3.0. Also checked if kid3 would give me any warning in case the tag is in weird format or encoding or anything but they seem to be all fine.

**Comment by jonaski** [comment]
It was a bug. Fixed now. I also added lyrics to the edit tag dialog.

**Comment by yekteniya** [comment]
Using build Version 0.5.5-146-gaa8679d, can see the lyrics editing dialog (appreciate it!) but its still not fetching the lyrics from the tag.

**Comment by jonaski** [comment]
It works here, tested with both FLAC and MP3

**Comment by yekteniya** [comment]
Reloaded the playlist and my collection and either of those things fixed it. Thanks again!

**Comment by jonaski** [comment]
I see. That makes sense, because it doesn't re-read the tags unless the files have changed, and since you had scanned the collection using a version with broken lyrics tagreader you still had the empty lyrics in the db.
So it definitely was the rescan that did the trick.
