### ISSUE TITLE
Scroll over icon to change track — ignored

### ISSUE THREAD

**Issue by alekksander** [jonaski/strawberry#51]
In settings behavior there is an option to change track on mouse wheel scroll. enabling this has no effect. if i recall correctly – if disabled – scrolling over icon should change volume inside app, but this doesn't happen either.

sorry for so many reports, but it's bug–hunting season here ;)

**Comment by jonaski** [comment]
Fixed in 4960142
This really shows how useful it is to have the automatic development builds and people like you who take the time to use them, it's a big help. Thanks!

**Comment by alekksander** [comment]
unfortunately it still doesn't work. You mention once You have two environments to test. does it works on both for You?

**Comment by jonaski** [comment]
I tested on KDE, does not work. Works on XFCE.
Clementine does not work in KDE either.
I think it may be that the tray icon on KDE works differently and does not trigger the eventFilter.

**Comment by alekksander** [comment]
i remember it used to work with clementine, so perhaps plasma bug. thanks for interest.

**Comment by davidedmundson** [comment]
It's not a plasma bug. 

Qt has multiple system tray backends

* The terrible 1980s embedding an X11 window
* https://www.freedesktop.org/wiki/Specifications/StatusNotifierItem/StatusNotifierItem/ 

Plasma uses the latter - Plasma  does send scroll events but using an EventFilter for things from the QPA isn't going to work.
